import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const browser = await chromium.launch();
const seite = await browser.newPage({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 1 });
await seite.goto('http://127.0.0.1:8933/spiel/?epoche=1&saat=1350&neu=1', { waitUntil: 'networkidle', timeout: 60000 });
await seite.waitForTimeout(700);
let z = await seite.evaluate(() => BRAUHAUS.zuege());
console.log('VOR anfangen, sud:', z.filter(x=>x.zug && x.zug.indexOf('sud:')===0).map(x=>x.zug+':'+x.offen));
const h = await seite.$('[data-zug="kern:anfangen"]');
const box = await h.boundingBox();
await seite.mouse.click(box.x+box.width/2, box.y+box.height/2);
await seite.waitForTimeout(200);
z = await seite.evaluate(() => BRAUHAUS.zuege());
console.log('NACH anfangen, sud:', z.filter(x=>x.zug && x.zug.indexOf('sud:')===0).map(x=>x.zug+':'+x.offen));
await browser.close();
